-- MySQL Script generated by MySQL Workbench
-- Sat Apr 27 11:22:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema farmacia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema farmacia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `farmacia` DEFAULT CHARACTER SET utf8 COLLATE utf8_estonian_ci ;
USE `farmacia` ;

-- -----------------------------------------------------
-- Table `farmacia`.`cat_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`cat_produto` (
  `idcat_produto` INT NOT NULL AUTO_INCREMENT,
  `tipo_produto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcat_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`promocao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`promocao` (
  `idpromocao` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`idpromocao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `cat_produto_idcat_produto` INT NOT NULL,
  `promocao_idpromocao` INT NOT NULL,
  PRIMARY KEY (`idproduto`),
  INDEX `fk_produto_cat_produto1_idx` (`cat_produto_idcat_produto` ASC) VISIBLE,
  INDEX `fk_produto_promocao1_idx` (`promocao_idpromocao` ASC) VISIBLE,
  CONSTRAINT `fk_produto_cat_produto1`
    FOREIGN KEY (`cat_produto_idcat_produto`)
    REFERENCES `farmacia`.`cat_produto` (`idcat_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_promocao1`
    FOREIGN KEY (`promocao_idpromocao`)
    REFERENCES `farmacia`.`promocao` (`idpromocao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`fornecedor` (
  `cnpj` VARCHAR(30) NOT NULL,
  `nome_empresa` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`receita` (
  `idreceita` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idreceita`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `Rua` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `Cep` INT NOT NULL,
  `Numero` INT NOT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`cliente` (
  `cpf` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `rg` INT NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `receita_idreceita` INT NOT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`cpf`),
  INDEX `fk_cliente_receita1_idx` (`receita_idreceita` ASC) VISIBLE,
  INDEX `fk_cliente_Endereco1_idx` (`Endereco_idEndereco` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_receita1`
    FOREIGN KEY (`receita_idreceita`)
    REFERENCES `farmacia`.`receita` (`idreceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `farmacia`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`desconto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`desconto` (
  `iddesconto` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`iddesconto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`cargo` (
  `idcargo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  `salario` DOUBLE NOT NULL,
  PRIMARY KEY (`idcargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`funcionario` (
  `cpf` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `rg` INT NOT NULL,
  `cargo_idcargo` INT NOT NULL,
  PRIMARY KEY (`cpf`),
  INDEX `fk_funcionario_cargo1_idx` (`cargo_idcargo` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_cargo1`
    FOREIGN KEY (`cargo_idcargo`)
    REFERENCES `farmacia`.`cargo` (`idcargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`venda` (
  `idvenda` INT NOT NULL AUTO_INCREMENT,
  `dt_venda` DATE NOT NULL,
  `desconto_iddesconto` INT NOT NULL,
  `funcionario_cpf` VARCHAR(15) NOT NULL,
  `cliente_cpf` VARCHAR(15) NOT NULL,
  `produto_idproduto` INT NOT NULL,
  PRIMARY KEY (`idvenda`),
  INDEX `fk_venda_desconto_idx` (`desconto_iddesconto` ASC) VISIBLE,
  INDEX `fk_venda_funcionario1_idx` (`funcionario_cpf` ASC) VISIBLE,
  INDEX `fk_venda_cliente1_idx` (`cliente_cpf` ASC) VISIBLE,
  INDEX `fk_venda_produto1_idx` (`produto_idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_venda_desconto`
    FOREIGN KEY (`desconto_iddesconto`)
    REFERENCES `farmacia`.`desconto` (`iddesconto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_funcionario1`
    FOREIGN KEY (`funcionario_cpf`)
    REFERENCES `farmacia`.`funcionario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `farmacia`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `farmacia`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`nota_fiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`nota_fiscal` (
  `idnota_fiscal` INT NOT NULL AUTO_INCREMENT,
  `venda_idvenda` INT NOT NULL,
  PRIMARY KEY (`idnota_fiscal`),
  INDEX `fk_nota_fiscal_venda1_idx` (`venda_idvenda` ASC) VISIBLE,
  CONSTRAINT `fk_nota_fiscal_venda1`
    FOREIGN KEY (`venda_idvenda`)
    REFERENCES `farmacia`.`venda` (`idvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`compra_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`compra_produtos` (
  `idcompra` INT NOT NULL AUTO_INCREMENT,
  `dt_compra` DATE NOT NULL,
  PRIMARY KEY (`idcompra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`item_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`item_compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `qtde` INT NOT NULL,
  `compra_produtos_idcompra` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_compra_compra_produtos1_idx` (`compra_produtos_idcompra` ASC) VISIBLE,
  CONSTRAINT `fk_item_compra_compra_produtos1`
    FOREIGN KEY (`compra_produtos_idcompra`)
    REFERENCES `farmacia`.`compra_produtos` (`idcompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`movimentacao_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`movimentacao_estoque` (
  `idmovimentacao_estoque` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `produto_idproduto` INT NOT NULL,
  `compra_produtos_idcompra` INT NOT NULL,
  PRIMARY KEY (`idmovimentacao_estoque`),
  INDEX `fk_movimentacao_estoque_produto1_idx` (`produto_idproduto` ASC) VISIBLE,
  INDEX `fk_movimentacao_estoque_compra_produtos1_idx` (`compra_produtos_idcompra` ASC) VISIBLE,
  CONSTRAINT `fk_movimentacao_estoque_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `farmacia`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimentacao_estoque_compra_produtos1`
    FOREIGN KEY (`compra_produtos_idcompra`)
    REFERENCES `farmacia`.`compra_produtos` (`idcompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`estoque` (
  `idestoque` INT NOT NULL AUTO_INCREMENT,
  `qtde` INT NOT NULL,
  `produto_idproduto` INT NOT NULL,
  PRIMARY KEY (`idestoque`),
  INDEX `fk_estoque_produto1_idx` (`produto_idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `farmacia`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`forma_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`forma_pagamento` (
  `idforma_pagamento` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idforma_pagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Tipo_Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Tipo_Entrega` (
  `idTipo_Entrega` INT NOT NULL AUTO_INCREMENT,
  `TipoEntrega` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipo_Entrega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Entrega` (
  `idEntrega` INT NOT NULL,
  `venda_idvenda` INT NOT NULL,
  `Tipo_Entrega_idTipo_Entrega` INT NOT NULL,
  PRIMARY KEY (`idEntrega`),
  INDEX `fk_Entrega_venda1_idx` (`venda_idvenda` ASC) VISIBLE,
  INDEX `fk_Entrega_Tipo_Entrega1_idx` (`Tipo_Entrega_idTipo_Entrega` ASC) VISIBLE,
  CONSTRAINT `fk_Entrega_venda1`
    FOREIGN KEY (`venda_idvenda`)
    REFERENCES `farmacia`.`venda` (`idvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrega_Tipo_Entrega1`
    FOREIGN KEY (`Tipo_Entrega_idTipo_Entrega`)
    REFERENCES `farmacia`.`Tipo_Entrega` (`idTipo_Entrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Pagamento` (
  `idPagamento` INT NOT NULL,
  `venda_idvenda` INT NOT NULL,
  `forma_pagamento_idforma_pagamento` INT NOT NULL,
  PRIMARY KEY (`idPagamento`),
  INDEX `fk_Pagamento_venda1_idx` (`venda_idvenda` ASC) VISIBLE,
  INDEX `fk_Pagamento_forma_pagamento1_idx` (`forma_pagamento_idforma_pagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento_venda1`
    FOREIGN KEY (`venda_idvenda`)
    REFERENCES `farmacia`.`venda` (`idvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagamento_forma_pagamento1`
    FOREIGN KEY (`forma_pagamento_idforma_pagamento`)
    REFERENCES `farmacia`.`forma_pagamento` (`idforma_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`compra_produtos_has_fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`compra_produtos_has_fornecedor` (
  `compra_produtos_idcompra` INT NOT NULL,
  `fornecedor_cnpj` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`compra_produtos_idcompra`, `fornecedor_cnpj`),
  INDEX `fk_compra_produtos_has_fornecedor_fornecedor1_idx` (`fornecedor_cnpj` ASC) VISIBLE,
  INDEX `fk_compra_produtos_has_fornecedor_compra_produtos1_idx` (`compra_produtos_idcompra` ASC) VISIBLE,
  CONSTRAINT `fk_compra_produtos_has_fornecedor_compra_produtos1`
    FOREIGN KEY (`compra_produtos_idcompra`)
    REFERENCES `farmacia`.`compra_produtos` (`idcompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_produtos_has_fornecedor_fornecedor1`
    FOREIGN KEY (`fornecedor_cnpj`)
    REFERENCES `farmacia`.`fornecedor` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
