-- MySQL Script generated by MySQL Workbench
-- Thu May 30 22:33:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema farmacia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema farmacia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `farmacia` DEFAULT CHARACTER SET utf8 COLLATE utf8_estonian_ci ;
USE `farmacia` ;

-- -----------------------------------------------------
-- Table `farmacia`.`Cat_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Cat_produto` (
  `idCat_produto` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCat_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Promocao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Promocao` (
  `idPromocao` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`idPromocao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `idCat_produto` INT NOT NULL,
  `idPromocao` INT NOT NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `fk_produto_cat_produto1_idx` (`idCat_produto` ASC) VISIBLE,
  INDEX `fk_produto_promocao1_idx` (`idPromocao` ASC) VISIBLE,
  CONSTRAINT `fk_produto_cat_produto1`
    FOREIGN KEY (`idCat_produto`)
    REFERENCES `farmacia`.`Cat_produto` (`idCat_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_promocao1`
    FOREIGN KEY (`idPromocao`)
    REFERENCES `farmacia`.`Promocao` (`idPromocao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Fornecedor` (
  `cnpj` INT NOT NULL,
  `nome_empresa` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Cliente` (
  `cpf` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `rg` INT NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Cargo` (
  `idCargo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  `salario` DOUBLE NOT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Funcionario` (
  `cpf` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `rg` INT NOT NULL,
  `idCargo` INT NOT NULL,
  PRIMARY KEY (`cpf`),
  INDEX `fk_funcionario_cargo1_idx` (`idCargo` ASC) VISIBLE,
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_cargo1`
    FOREIGN KEY (`idCargo`)
    REFERENCES `farmacia`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Desconto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Desconto` (
  `idDesconto` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`idDesconto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Compra_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Compra_produtos` (
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `dt_compra` DATE NOT NULL,
  `Fornecedor_cnpj` INT NOT NULL,
  PRIMARY KEY (`idCompra`),
  INDEX `fk_Compra_produtos_Fornecedor1_idx` (`Fornecedor_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_produtos_Fornecedor1`
    FOREIGN KEY (`Fornecedor_cnpj`)
    REFERENCES `farmacia`.`Fornecedor` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Item_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Item_compra` (
  `idItem` INT NOT NULL AUTO_INCREMENT,
  `qtde` INT NOT NULL,
  `nome_produto` VARCHAR(45) NOT NULL,
  `Compra_produtos_idCompra` INT NOT NULL,
  PRIMARY KEY (`idItem`),
  INDEX `fk_Item_compra_Compra_produtos1_idx` (`Compra_produtos_idCompra` ASC) VISIBLE,
  CONSTRAINT `fk_Item_compra_Compra_produtos1`
    FOREIGN KEY (`Compra_produtos_idCompra`)
    REFERENCES `farmacia`.`Compra_produtos` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Estoque` (
  `idEstoque` INT NOT NULL AUTO_INCREMENT,
  `qtde` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Item_compra_idItem` INT NOT NULL,
  PRIMARY KEY (`idEstoque`),
  INDEX `fk_Estoque_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Estoque_Item_compra1_idx` (`Item_compra_idItem` ASC) VISIBLE,
  CONSTRAINT `fk_Estoque_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `farmacia`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estoque_Item_compra1`
    FOREIGN KEY (`Item_compra_idItem`)
    REFERENCES `farmacia`.`Item_compra` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Venda` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `dt_venda` DATE NOT NULL,
  `qtde` INT NOT NULL,
  `valorTotal` DOUBLE NOT NULL,
  `cpfFuncionario` INT NOT NULL,
  `cpfCliente` INT NOT NULL,
  `idDesconto` INT NOT NULL,
  `Estoque_idEstoque` INT NOT NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `fk_venda_funcionario1_idx` (`cpfFuncionario` ASC) VISIBLE,
  INDEX `fk_venda_cliente1_idx` (`cpfCliente` ASC) VISIBLE,
  INDEX `fk_venda_Desconto1_idx` (`idDesconto` ASC) VISIBLE,
  INDEX `fk_Venda_Estoque1_idx` (`Estoque_idEstoque` ASC) VISIBLE,
  CONSTRAINT `fk_venda_funcionario1`
    FOREIGN KEY (`cpfFuncionario`)
    REFERENCES `farmacia`.`Funcionario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cpfCliente`)
    REFERENCES `farmacia`.`Cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_Desconto1`
    FOREIGN KEY (`idDesconto`)
    REFERENCES `farmacia`.`Desconto` (`idDesconto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `farmacia`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Nota_fiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Nota_fiscal` (
  `idNota_fiscal` INT NOT NULL AUTO_INCREMENT,
  `idVenda` INT NOT NULL,
  PRIMARY KEY (`idNota_fiscal`),
  INDEX `fk_nota_fiscal_venda1_idx` (`idVenda` ASC) VISIBLE,
  CONSTRAINT `fk_nota_fiscal_venda1`
    FOREIGN KEY (`idVenda`)
    REFERENCES `farmacia`.`Venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Receita` (
  `idReceita` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `cpfCliente` INT NOT NULL,
  PRIMARY KEY (`idReceita`),
  INDEX `fk_receita_cliente1_idx` (`cpfCliente` ASC) VISIBLE,
  CONSTRAINT `fk_receita_cliente1`
    FOREIGN KEY (`cpfCliente`)
    REFERENCES `farmacia`.`Cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Forma_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Forma_pagamento` (
  `idForma_pagamento` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idForma_pagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Tipo_Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Tipo_Entrega` (
  `idTipo_entrega` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_entrega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Entrega` (
  `idEntrega` INT NOT NULL,
  `idVenda` INT NOT NULL,
  `idTipo_Entrega` INT NOT NULL,
  `idStatusEntrega` INT NOT NULL,
  PRIMARY KEY (`idEntrega`),
  INDEX `fk_Entrega_venda1_idx` (`idVenda` ASC) VISIBLE,
  INDEX `fk_Entrega_Tipo_Entrega1_idx` (`idTipo_Entrega` ASC) VISIBLE,
  CONSTRAINT `fk_Entrega_venda1`
    FOREIGN KEY (`idVenda`)
    REFERENCES `farmacia`.`Venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrega_Tipo_Entrega1`
    FOREIGN KEY (`idTipo_Entrega`)
    REFERENCES `farmacia`.`Tipo_Entrega` (`idTipo_entrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Pagamento` (
  `idPagamento` INT NOT NULL,
  `idVenda` INT NOT NULL,
  `idForma_pagamento` INT NOT NULL,
  PRIMARY KEY (`idPagamento`),
  INDEX `fk_Pagamento_venda1_idx` (`idVenda` ASC) VISIBLE,
  INDEX `fk_Pagamento_forma_pagamento1_idx` (`idForma_pagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento_venda1`
    FOREIGN KEY (`idVenda`)
    REFERENCES `farmacia`.`Venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagamento_forma_pagamento1`
    FOREIGN KEY (`idForma_pagamento`)
    REFERENCES `farmacia`.`Forma_pagamento` (`idForma_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `cep` INT NOT NULL,
  `numero` INT NOT NULL,
  `cpfCliente` INT NOT NULL,
  PRIMARY KEY (`idEndereco`),
  INDEX `fk_Endereco_cliente1_idx` (`cpfCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_cliente1`
    FOREIGN KEY (`cpfCliente`)
    REFERENCES `farmacia`.`Cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
